/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tourandtravel;

import Controller.loginControl;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author PREDATOR
 */
public class LoginPage extends javax.swing.JFrame {
    // Attribute
    public static boolean remember = false;
    public boolean hidden = true;
    private Point initialClick;
    loginControl control = new loginControl();
    File rememberFile = new File("rememberMeLogin.txt");
    private JFrame parent;
    

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        passwordField.setEchoChar((char)8226);
        cekStatusSql();
        control.cekSqlTimer();
        control.readRemember();
        
        // Untuk memindahkan jframe
        parent = this;
        panelFirst.addMouseListener(new MouseAdapter() { 
            public void mousePressed(MouseEvent e) { 
                initialClick = e.getPoint(); 
                getComponentAt(initialClick); 
            }
        });

        panelFirst.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {

                    // get location of Window
                    int thisX = parent.getLocation().x;
                    int thisY = parent.getLocation().y;

                    // Determine how much the mouse moved since the initial click
                    int xMoved = e.getX() - initialClick.x;
                    int yMoved = e.getY() - initialClick.y;

                    // Move window to this position
                    int X = thisX + xMoved;
                    int Y = thisY + yMoved;
                    parent.setLocation(X, Y);
                }
            });
        
        panelSecond.addMouseListener(new MouseAdapter() { 
            public void mousePressed(MouseEvent e) { 
                initialClick = e.getPoint(); 
                getComponentAt(initialClick); 
            }
        });

        panelSecond.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {

                    // get location of Window
                    int thisX = parent.getLocation().x;
                    int thisY = parent.getLocation().y;

                    // Determine how much the mouse moved since the initial click
                    int xMoved = e.getX() - initialClick.x;
                    int yMoved = e.getY() - initialClick.y;

                    // Move window to this position
                    int X = thisX + xMoved;
                    int Y = thisY + yMoved;
                    parent.setLocation(X, Y);
                }
            });
    }
    
    public final void cekStatusSql() {
        if(control.checkConnection()) {
            sqlStatusLabel.setText("Online");
            sqlStatusLabel.setForeground(new java.awt.Color(51,255,51));
        } else {
            sqlStatusLabel.setText("Offline");
            sqlStatusLabel.setForeground(new java.awt.Color(255,0,0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFirst = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelSecond = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        hidePassword = new javax.swing.JLabel();
        rememberMe = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sqlStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tour & Travel: Log-in");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFirst.setBackground(new java.awt.Color(25, 118, 211));
        panelFirst.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Abstract.png"))); // NOI18N
        panelFirst.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        getContentPane().add(panelFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        panelSecond.setBackground(new java.awt.Color(255, 255, 255));
        panelSecond.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoAppResizePlus.png"))); // NOI18N
        panelSecond.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 22, 217, 69));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitIconMouseExited(evt);
            }
        });
        panelSecond.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 6, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");
        panelSecond.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 330, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hello, Welcome Back!");
        panelSecond.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 330, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Username");
        panelSecond.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 235, -1));

        usernameField.setBackground(new java.awt.Color(255, 255, 255));
        usernameField.setFont(usernameField.getFont().deriveFont(usernameField.getFont().getSize()+2f));
        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        panelSecond.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 20));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("________________________________");
        panelSecond.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 31));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        panelSecond.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password");
        panelSecond.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 235, -1));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setFont(passwordField.getFont().deriveFont(passwordField.getFont().getSize()+2f));
        passwordField.setBorder(null);
        panelSecond.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 20));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("________________________________");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelSecond.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 40));

        hidePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye-Invisible.png"))); // NOI18N
        hidePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePasswordMouseClicked(evt);
            }
        });
        panelSecond.add(hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        rememberMe.setForeground(new java.awt.Color(102, 102, 102));
        rememberMe.setText("Remember Me?");
        rememberMe.setFocusable(false);
        rememberMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rememberMeMouseClicked(evt);
            }
        });
        panelSecond.add(rememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 271, -1, -1));

        loginButton.setBackground(new java.awt.Color(255, 153, 102));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusable(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panelSecond.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 303, 280, 33));

        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("by Muhammad Olfat Faiz");
        panelSecond.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 140, -1));

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("MySQL Status:");
        panelSecond.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, -1));

        sqlStatusLabel.setForeground(new java.awt.Color(255, 0, 0));
        sqlStatusLabel.setText("Offline");
        panelSecond.add(sqlStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 350, 40, -1));

        getContentPane().add(panelSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 330, 380));

        setSize(new java.awt.Dimension(699, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitIconMouseClicked

    private void exitIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseEntered
        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit_Red.png")));
    }//GEN-LAST:event_exitIconMouseEntered

    private void exitIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseExited
        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png")));
    }//GEN-LAST:event_exitIconMouseExited

    private void hidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePasswordMouseClicked
        if(hidden) {
            hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye.png")));
            passwordField.setEchoChar((char)0);
            hidden = false;
        } else {
            hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye-Invisible.png")));
            passwordField.setEchoChar((char)8226);
            hidden = true;
        }
    }//GEN-LAST:event_hidePasswordMouseClicked

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        cekStatusSql();
        if(control.checkEntry()) {
            new HalamanUtama().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void rememberMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rememberMeMouseClicked
        if(rememberMe.isSelected()) {
            remember = true;
        } else {
            remember = false;
            if(rememberFile.exists()) {
                rememberFile.delete();   
            }
        }
    }//GEN-LAST:event_rememberMeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel hidePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelFirst;
    private javax.swing.JPanel panelSecond;
    public static javax.swing.JPasswordField passwordField;
    public static javax.swing.JCheckBox rememberMe;
    public static javax.swing.JLabel sqlStatusLabel;
    public static javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
